export const types = {
	LOAD_PARTNER_CUSTOMERS: 'PARTNER/LOAD_PARTNER_CUSTOMERS',
	PARTNER_CUSTOMERS_LOADED: 'PARTNER/PARTNER_CUSTOMERS_LOADED',
	APPROVE_APPLICATION: 'PARTNER/APPROVE_APPLICATION',
	LOAD_FUTURE_INSTALLMENTS: 'PARTNER/LOAD_FUTURE_INSTALLMENTS',
	FUTURE_INSTALLMENTS_LOADED: 'PARTNER/FUTURE_INSTALLMENTS_LOADED',
	LOAD_PAST_INSTALLMENTS: 'PARTNER/LOAD_PAST_INSTALLMENTS',
	PAST_INSTALLMENTS_LOADED: 'PARTNER/PAST_INSTALLMENTS_LOADED',
	LOAD_INVOICES: 'PARTNER/LOAD_INVOICES',
	INVOICES_LOADED: 'PARTNER/INVOICES_LOADED',
	LOAD_PARTNER_CREDIT_INFORMATION: 'PARTNER/LOAD_PARTNER_CREDIT_INFORMATION',
	PARTNER_CREDIT_INFORMATION_LOADED: 'PARTNER/PARTNER_CREDIT_INFORMATION_LOADED',
	UPDATE_INSTALLMENT_COMMENT: 'COMMON/UPDATE_INSTALLMENT_COMMENT',
};
