export const types = {
	LOAD_CUSTOMER_DOCUMENTS: 'COMMON/LOAD_CUSTOMER_DOCUMENTS', // load customer documents by customer id
	CUSTOMER_DOCUMENTS_LOADED: 'COMMON/CUSTOMER_DOCUMENTS_LOADED',
	LOAD_CUSTOMER_MAIN: 'COMMON/LOAD_CUSTOMER_MAIN',
	CUSTOMER_MAIN_LOADED: 'COMMON/CUSTOMER_MAIN_LOADED',
	ERROR_MESSAGE: 'COMMON/ERROR_MESSAGE',
	LOAD_CREDIT_CHANGE_LOG: 'COMMON/LOAD_CREDIT_CHANGE_LOG',
	CREDIT_CHANGE_LOG_LOADED: 'COMMON/CREDIT_CHANGE_LOG_LOADED',
};
