export const types = {
	LOAD_ALL_PARTNERS: 'MTAJI/LOAD_ALL_PARTNERS',
	ALL_PARTNERS_LOADED: 'MTAJI/ALL_PARTNERS_LOADED',
	LOAD_ALL_CUSTOMERS: 'MTAJI/LOAD_ALL_CUSTOMERS',
	ALL_CUSTOMERS_LOADED: 'MTAJI/ALL_CUSTOMERS_LOADED',
};
